name: bhandara_live
description: Bhandara Live - Find and share community Bhandara events near you.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  http_parser: ^4.1.2
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  intl: ^0.20.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shared_preferences: ^2.3.4
  uuid: ^4.5.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  supabase_flutter: ^2.9.0
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
